//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nocturne.BL.HelperServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdCardData", Namespace="http://schemas.datacontract.org/2004/07/CardHelper")]
    [System.SerializableAttribute()]
    public partial class IdCardData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCode {
            get {
                return this.IdCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCodeField, value) != true)) {
                    this.IdCodeField = value;
                    this.RaisePropertyChanged("IdCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelperServiceReference.IHelperService")]
    public interface IHelperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelperService/GetIdCardFromReader", ReplyAction="http://tempuri.org/IHelperService/GetIdCardFromReaderResponse")]
        Nocturne.BL.HelperServiceReference.IdCardData GetIdCardFromReader();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelperService/GetIdCardFromReader", ReplyAction="http://tempuri.org/IHelperService/GetIdCardFromReaderResponse")]
        System.Threading.Tasks.Task<Nocturne.BL.HelperServiceReference.IdCardData> GetIdCardFromReaderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelperService/GetRfidCardFromReader", ReplyAction="http://tempuri.org/IHelperService/GetRfidCardFromReaderResponse")]
        System.Nullable<ulong> GetRfidCardFromReader();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelperService/GetRfidCardFromReader", ReplyAction="http://tempuri.org/IHelperService/GetRfidCardFromReaderResponse")]
        System.Threading.Tasks.Task<System.Nullable<ulong>> GetRfidCardFromReaderAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelperServiceChannel : Nocturne.BL.HelperServiceReference.IHelperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelperServiceClient : System.ServiceModel.ClientBase<Nocturne.BL.HelperServiceReference.IHelperService>, Nocturne.BL.HelperServiceReference.IHelperService {
        
        public HelperServiceClient() {
        }
        
        public HelperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Nocturne.BL.HelperServiceReference.IdCardData GetIdCardFromReader() {
            return base.Channel.GetIdCardFromReader();
        }
        
        public System.Threading.Tasks.Task<Nocturne.BL.HelperServiceReference.IdCardData> GetIdCardFromReaderAsync() {
            return base.Channel.GetIdCardFromReaderAsync();
        }
        
        public System.Nullable<ulong> GetRfidCardFromReader() {
            return base.Channel.GetRfidCardFromReader();
        }
        
        public System.Threading.Tasks.Task<System.Nullable<ulong>> GetRfidCardFromReaderAsync() {
            return base.Channel.GetRfidCardFromReaderAsync();
        }
    }
}
